load_name: reservoir_12col_21ml
display_name: 12-Column Trough Reservoir 21 mL
brand: Generic
brand_ids: []
namespace: custom_beta
version: 1
display_category: reservoir
plate_format: trough
rows: 1
cols: 12
x_offset: 13.94
y_offset: 42.74
x_spacing: 9.0
y_spacing: 0.0
well_z: null
shape: rectangular
diameter: null
x_length: 8.2
y_length: 71.2
depth: 39.22
total_liquid_volume: 21000
well_bottom_shape: flat
x_dimension: 127.76
y_dimension: 85.48
z_dimension: 44.14
is_tiprack: false
tip_length: null
tip_overlap: null
is_magnetic_module_compatible: false
quirks: []
