load_name: standard_6_wellplate_16800ul
display_name: Standard 6-Well Plate 16800 µL
brand: Generic
brand_ids: []
namespace: custom_beta
version: 1
display_category: wellPlate
plate_format: irregular
rows: 2
cols: 3
x_offset: 24.76
y_offset: 65.52
x_spacing: 39.12
y_spacing: 39.12
well_z: null
shape: circular
diameter: 35.0
x_length: null
y_length: null
depth: 17.4
total_liquid_volume: 16800
well_bottom_shape: flat
x_dimension: 127.76
y_dimension: 85.48
z_dimension: 20.0
is_tiprack: false
tip_length: null
tip_overlap: null
is_magnetic_module_compatible: false
quirks: []
