load_name: standard_24_wellplate_3400ul
display_name: Standard 24-Well Plate 3400 µL
brand: Generic
brand_ids: []
namespace: custom_beta
version: 1
display_category: wellPlate
plate_format: irregular
rows: 4
cols: 6
x_offset: 17.05
y_offset: 76.0
x_spacing: 19.3
y_spacing: 19.3
well_z: null
shape: circular
diameter: 15.62
x_length: null
y_length: null
depth: 17.4
total_liquid_volume: 3400
well_bottom_shape: flat
x_dimension: 127.76
y_dimension: 85.48
z_dimension: 20.0
is_tiprack: false
tip_length: null
tip_overlap: null
is_magnetic_module_compatible: false
quirks: []
