"""Emit a standalone OT-2 protocol from a resolved workflow.

The emitted file is a small interpreter over the recorded operation list.  It
computes nothing: every volume, height, and well was decided by the resolver and
verified by simulation before this file existed.  That is what keeps the
uploaded protocol identical to what was simulated.

Nothing here is written by a language model.  The generator is deterministic, so
the same resolved workflow always produces byte-identical Python.
"""

from __future__ import annotations

import json
from pathlib import Path

from .resolver import ResolvedWorkflowV1

_TEMPLATE = '''"""SERS experiment protocol - GENERATED, do not edit by hand.

Experiment    {experiment_name}  [{experiment_id}]
Profile       {machine_profile_id}
Config hash   {config_hash}
Resolved hash {resolved_hash}
Generated by  src/sers_engine/emitter.py

Every operation below was resolved and simulated before this file was written.
Editing it breaks the hash binding that authorizes the run.
"""

metadata = {{
    "protocolName": "SERS {experiment_name}",
    "author": "sers_engine",
    "description": {description!r},
    "apiLevel": "{api_level}",
}}

RESOLVED_HASH = "{resolved_hash}"
CONFIG_HASH = "{config_hash}"

DECK = {deck!r}

OPERATIONS = json.loads("""{operations}""")


def _point(labware_by_role, entry):
    well = labware_by_role[entry["labware"]].wells_by_name()[entry["well"]]
    return well.top(entry["z"]) if entry["reference"] == "top" else well.bottom(entry["z"])


def run(protocol):
    protocol.comment("SERS experiment {experiment_name} [{experiment_id}]")
    protocol.comment("resolved hash {resolved_hash}")

    labware_by_role = {{}}
    tip_racks = []
    for role, spec in DECK["labware"].items():
        kwargs = {{}}
        if spec.get("namespace") and spec["namespace"] != "opentrons":
            kwargs["namespace"] = spec["namespace"]
            if spec.get("version") is not None:
                kwargs["version"] = spec["version"]
        loaded = protocol.load_labware(spec["load_name"], str(spec["slot"]), **kwargs)
        labware_by_role[role] = loaded
        if spec["kind"] == "tiprack":
            tip_racks.append(loaded)

    pipette = protocol.load_instrument(
        DECK["pipette"]["name"], DECK["pipette"]["mount"], tip_racks=tip_racks
    )
    pipette.flow_rate.aspirate = DECK["pipette"]["aspirate_flow_rate_ul_s"]
    pipette.flow_rate.dispense = DECK["pipette"]["dispense_flow_rate_ul_s"]

    for entry in OPERATIONS:
        action = entry["op"]
        if action == "comment":
            protocol.comment(entry["text"])
        elif action == "delay":
            protocol.delay(seconds=entry["seconds"])
        elif action == "pick_up_tip":
            pipette.pick_up_tip(
                labware_by_role[entry["labware"]].wells_by_name()[entry["well"]]
            )
        elif action == "drop_tip":
            pipette.drop_tip()
        elif action == "return_tip":
            pipette.return_tip()
        elif action == "aspirate":
            pipette.aspirate(entry["volume"], _point(labware_by_role, entry))
        elif action == "dispense":
            target = _point(labware_by_role, entry)
            if "push_out" in entry:
                try:
                    pipette.dispense(entry["volume"], target, push_out=entry["push_out"])
                except TypeError:
                    pipette.dispense(entry["volume"], target)
            else:
                pipette.dispense(entry["volume"], target)
        elif action == "air_gap":
            pipette.air_gap(entry["volume"], height=entry["height"])
        elif action == "blow_out":
            pipette.blow_out(_point(labware_by_role, entry))
        elif action == "mix":
            pipette.mix(
                entry["repetitions"], entry["volume"], _point(labware_by_role, entry)
            )
        elif action == "move_to":
            pipette.move_to(_point(labware_by_role, entry))
        elif action == "touch_tip":
            pipette.touch_tip(
                labware_by_role[entry["labware"]].wells_by_name()[entry["well"]]
            )
        else:
            raise ValueError("unknown operation: " + action)

    protocol.comment("SERS experiment complete")
'''


def emit_protocol(plan: ResolvedWorkflowV1) -> str:
    """Render the standalone protocol source for one resolved workflow."""
    config = plan.as_experiment_config()
    deck = {
        "labware": {
            role: {
                "slot": spec.slot,
                "kind": spec.kind,
                "load_name": spec.load_name,
                "namespace": spec.namespace,
                "version": spec.version,
            }
            for role, spec in {
                **config.deck_layout.labware,
                **config.deck_layout.tip_racks,
            }.items()
        },
        "pipette": {
            "name": config.pipette.name,
            "mount": config.pipette.mount,
            "aspirate_flow_rate_ul_s": config.pipette.aspirate_flow_rate_ul_s,
            "dispense_flow_rate_ul_s": config.pipette.dispense_flow_rate_ul_s,
        },
    }
    body = _TEMPLATE.format(
        experiment_name=plan.experiment_name,
        experiment_id=plan.experiment_id,
        machine_profile_id=plan.machine_profile_id,
        config_hash=plan.config_hash,
        resolved_hash=plan.resolved_hash,
        description=plan.description or plan.experiment_name,
        api_level=config.api_level,
        deck=deck,
        operations=json.dumps(plan.operations, indent=1),
    )
    return "import json\n\n" + body


def write_protocol(plan: ResolvedWorkflowV1, directory: Path) -> Path:
    """Write the emitted protocol beside the run's other artifacts."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{plan.experiment_id}_{plan.resolved_hash[:12]}.py"
    path.write_text(emit_protocol(plan), encoding="utf-8")
    return path
